package edu.uw.zookeeper.clients.trace;

public enum TraceEventTag {
    NONE_EVENT,
    TIMESTAMP_EVENT,
    PROTOCOL_REQUEST_EVENT,
    PROTOCOL_RESPONSE_EVENT,
    OPERATION_EVENT,
    LATENCY_MEASUREMENT_EVENT,
    THROUGHPUT_MEASUREMENT_EVENT;
}
